name = "url-monitor"
compatibility_date = "2024-06-22"
compatibility_flags = ["nodejs_compat"]

pages_build_output_dir = "dist"

# KV binding for storage
[[kv_namespaces]]
binding = "URL_MONITOR_KV"
id = "your_kv_namespace_id_here"